imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        save_path:  null

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ad_client:  %ad_client%
        ga_tracking:  %ga_tracking%
        supported_locales:  %supported_locales%
        locale_names:  %locale_names%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [IntractoSecretSantaBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: true

jms_i18n_routing:
    default_locale: "%locale%"
    locales: %supported_locales%
    strategy: prefix_except_default

jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
genemu_form:
    tinymce:
        enabled: true
        theme:   advanced
    date: ~

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
    twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    intracto.twig.linkify_extension:
        class: Intracto\SecretSantaBundle\Twig\LinkifyExtension
        tags:
            - { name: twig.extension }

    cache:
        class: Doctrine\Common\Cache\ApcCache

    pool_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - IntractoSecretSantaBundle:Pool

    entry_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - IntractoSecretSantaBundle:Entry

    intracto_secretsanta.send_pending_confirmation_mail_listener:
        class: Intracto\SecretSantaBundle\EventListener\SendPendingConfirmationMailListener
        arguments:
            - @templating
            - @mailer
            - "%admin_email%"
            - @translator
        tags:
            - { name: kernel.event_subscriber }

    intracto.locale_listener:
        class: Intracto\SecretSantaBundle\EventListener\LocaleListener
        arguments: ["%supported_locales%", @jms_i18n_routing.router]
        tags:
            - { name: kernel.event_subscriber }

    intracto.validator.entry_has_valid_excludes:
        class: Intracto\SecretSantaBundle\Validator\EntryHasValidExcludesValidator
        tags:
            - { name: validator.constraint_validator, alias: intracto.validator.entry_has_valid_excludes }
    intracto.validator.pool_has_valid_excludes:
        class: Intracto\SecretSantaBundle\Validator\PoolHasValidExcludesValidator
        arguments:
            - @intracto_secret_santa.entry_shuffler
        tags:
            - { name: validator.constraint_validator, alias: intracto.validator.pool_has_valid_excludes }

    intracto_secret_santa.entry_shuffler:
        class: Intracto\SecretSantaBundle\Entity\EntryShuffler
