intracto_secret_santa:
    resource: "@IntractoSecretSantaBundle/Controller/"
    type:     annotation
    prefix:   /

privacy:
    path: /privacy
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'IntractoSecretSantaBundle:Static:privacyPolicy.html.twig'

faq:
    path: /faq
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'IntractoSecretSantaBundle:Static:faq.html.twig'
