imports:
    - { resource: legacy_aliases.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $geoIpDbPath: '%geo_ip_db_path%'
<<<<<<< HEAD
            $reportCachePath: '%kernel.project_dir%/var/report_cache'
=======
            $recaptchaSecret: '%kernel.root_dir%/config/recaptcha_secrets.json'
>>>>>>> SANTA-99: keys in jsonfile

    Intracto\SecretSantaBundle\:
        resource: '../../src/Intracto/SecretSantaBundle/*'
        exclude: '../../src/Intracto/SecretSantaBundle/{Entity,Tests,Query/GaParameters.php,Query/NoResultException.php,Resources}'

    Intracto\SecretSantaBundle\Controller\:
        resource: '../../src/Intracto/SecretSantaBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Intracto\SecretSantaBundle\Mailer\MailerService:
        arguments:
            $mailer: '@swiftmailer.mailer.mailer'
            $mandrill: '@swiftmailer.mailer.mandrill'
            $noreplyEmail: '%noreply_email%'
            $contactEmail: '%contact_email%'

    Intracto\SecretSantaBundle\Query\GoogleAnalyticsQuery:
        arguments:
            $viewId: '%ga_view_id%'
            $clientSecret: '%kernel.root_dir%/config/client_secrets.json'

    Intracto\SecretSantaBundle\Form\Extension\DateTypeExtension:
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }

    Doctrine\Common\Cache\ApcuCache: ~
    Twig\Extensions\TextExtension: ~
    Twig\Extensions\IntlExtension: ~

    Symfony\Component\Form\FormRendererInterface: '@twig.form.renderer'
